services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    container_name: shadowrun-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=5m               
      - OLLAMA_MAX_LOADED_MODELS=2         
      - OLLAMA_NUM_PARALLEL=1              
      - OLLAMA_NUM_GPU=1
      - OLLAMA_FLASH_ATTENTION=1
    networks:
      - shadowrun-net
    healthcheck:
      test: ["CMD", "true"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 60s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shadowrun-backend-simple
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:rw
      - ./backend:/app/backend
      - ./tools:/app/tools
      - ./cache/marker:/root/.cache/datalab
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Back to Docker Ollama
      - EMBEDDING_MODEL=nomic-embed-text
      - LLM_MODEL=qwen2.5:14b-instruct-q6_K
      
      # Simplified settings - only what's needed
      - MODEL_TEMPERATURE=0.7              
      - MODEL_TOP_P=0.8
      - MODEL_REPEAT_PENALTY=1.05
      - MODEL_NUM_CTX=8192
      
      # Chroma settings
      - CHROMA_DB_PATH=/app/data/chroma_db
      - COLLECTION_NAME=shadowrun_docs
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - shadowrun-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: shadowrun-frontend-simple
    ports:
      - "8501:7860"  # Map to port 8501 for consistency
    volumes:
      - ./frontend:/app/frontend
      - ./data:/app/data:ro  # Read-only for frontend
    environment:
      - API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - shadowrun-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  shadowrun-net:
    driver: bridge

volumes:
  ollama_data:
    driver: local